tasks:
  - name: terraform
    env:
      TF_LOG: DEBUG
    before: |
      # Set default project root if not already defined
      PROJECT_ROOT=${PROJECT_ROOT:-/workspace/DevOps-Terraform-Ansible-Jenkins}

      cd $PROJECT_ROOT  

      # Install Terraform CLI if not already installed
      source ./bin/install_terraform_cli

      # Generate Terraform credentials (if the script exists)
      if [ -f ./bin/generate_tfrc_credentials ]; then
        source ./bin/generate_tfrc_credentials
      fi

      # Set Terraform alias (if the script exists)
      if [ -f ./bin/set_tf_alias ]; then
        source ./bin/set_tf_alias
      fi

      # Copy example terraform.tfvars if it doesn't exist
      if [ ! -f $PROJECT_ROOT/terraform.tfvars ]; then
        cp $PROJECT_ROOT/terraform.tfvars.example $PROJECT_ROOT/terraform.tfvars
      fi

      # Build provider (if the script exists)
      if [ -f ./bin/build_provider ]; then
        source ./bin/build_provider
      fi

      # Initialize Terraform
      echo "Running terraform init..."
      terraform init

  - name: install-aws-cli
    before: |
      if ! command -v aws &> /dev/null; then
        echo "AWS CLI not found. Installing..."
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        rm -rf awscliv2.zip aws
        echo "AWS CLI installed!"
      fi

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
